---
title: "Math598FinalProject"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data = read.csv('/Users/dr.z/Desktop/Math 598 Final Project/chart.csv')
#View(data)
```

```{r}
data$DateTime = as.POSIXct(data$DateTime)
plot(data$DateTime, data$Users, type='l', col='blue')
```

```{r}
data2 = data[data$DateTime >= "2015-01-01" & data$DateTime < "2020-03-10",]
plot(data2$DateTime, data2$Users, type='l', col='blue')
```

```{r}
logUsers2 = log(data2$Users)
plot(data2$DateTime, logUsers2, type='l', col='blue')
```

```{r}
acf(logUsers2, na.action = na.pass)
pacf(logUsers2, na.action = na.pass)
```

```{r}
diff_Users2 = diff(logUsers2)
acf(diff_Users2, na.action = na.pass)
pacf(diff_Users2, na.action = na.pass)
```

```{r}
diff2_Users2 = diff(diff_Users2, 7)
acf(diff2_Users2, na.action = na.pass)
pacf(diff2_Users2, na.action = na.pass)
```

```{r}
library(astsa)
sarima(data2$Users, 1, 1, 0, P = 1, D = 1, Q = 0, S = 7)
```

```{r}
sarima.for(data2$Users, 5, 1,1,0, 1,1,0,7)
```


